### ISSUE TITLE
reduce entropy

### ISSUE THREAD

**Issue by kruftik** [kha7iq/drl-exporter#1]
a couple of weeks ago I did the similar thing (https://github.com/kruftik/dockerhub-pulllimits-exporter) but almost nothing has been done to advertise the service.

in order not to increase entropy of the universe, I'd rather to deprecate my repository and will direct all the visitors to your service.

**Comment by ma7ik** [comment]
Thank you @kruftik i appreciate it. 
I have seen that you created a helm chart as well. I am very open to any contribution :)
