### ISSUE TITLE
no header data for limit / Error collecting metrics: no reqsource label found

### ISSUE THREAD

**Issue by jk** [kha7iq/drl-exporter#11]
**Describe the bug**

I'm using the image with `ENABLE_USER_AUTH=true` and set `DOCKERHUB_USER` + `DOCKERHUB_PASSWORD` to my paid docker account (Docker Team). When running the image I get the following errors:

```
2024/11/18 13:54:59 Error collecting metrics: no reqsource label found
2024/11/18 13:55:14 Error collecting metrics: no reqsource label found
drl-exporter 2024/11/18 13:55:14 no header data for limit
2024/11/18 13:55:30 Error collecting metrics: no reqsource label found
drl-exporter 2024/11/18 13:55:30 no header data for limit
```

The `/metrics` endpoint lacks the dockerhub_ metrics. When I'm supplying a wrong password in `DOCKERHUB_PASSWORD` I get the expected error, that it wasn't able to authenticate. When I'm not using any auth at all it works for the unauthenticated rate limits, as expected.

**To Reproduce**

1. Set `ENABLE_USER_AUTH=true`
2. Set `DOCKERHUB_USER` to valid paid account name
3. Set `DOCKERHUB_PASSWORD` to valid paid account password
4. Start the image
5. See the container log output

**Expected behavior**

Get higher rate limits in metrics for my authenticated account.

**Additional context**

I'm using the latest image as of today (2024-11-18) `ghcr.io/kha7iq/drl-exporter:latestghcr.io/kha7iq/drl-exporter:latest`.

**Comment by kha7iq** [comment]
I will try to reproduce this an check

**Comment by kha7iq** [comment]
@jk 
Can you check if your password or user value is in quotes `""` and try without it ?
I have tested at my end and it works.
i.e 
```yaml
    environment:
      - DOCKERHUB_USER=username
      - DOCKERHUB_PASSWORD=password
      - ENABLE_USER_AUTH=true
 ```

**Comment by kha7iq** [comment]
Closing as no answer, reopen if you need to.

**Comment by jk** [comment]
@kha7iq Sorry, I overlooked your second message with the request. I will test it tonight and report back.

**Comment by jk** [comment]
@kha7iq I've just looked at it. I wasn't using quotes. But out of curiosity I also tried 

```yaml
    environment:
      - 'DOCKERHUB_USER=username'
      - 'DOCKERHUB_PASSWORD=password'
      - 'ENABLE_USER_AUTH=true'
```

But both (with and without single quotes) does not work.
