### ISSUE TITLE
Feature: Add prometheus request source label

### ISSUE THREAD

**Issue by jortkoopmans** [kha7iq/drl-exporter#2]
Hi @kha7iq, thanks for creating this implementation.
Perhaps you have abandoned this project, but maybe you're interested to add a feature that I've created that add a label to prometheus metrics to view the request source (which is also extracted from the response headers). This can be useful when tracking different source IP addresses or docker hub account names.

See PR linked.

**Comment by kha7iq** [comment]
Hello @jortkoopmans  
The project is not abandoned but i feel like it still does what it was built to do. 
I appreciate you spending time to make it better. I will merge the PR hoping you have already tested everything.

**Comment by jortkoopmans** [comment]
Thanks a lot @kha7iq , yes I have tested it on my side.
