### ISSUE TITLE
Cloud you please release new image version with security patches

### ISSUE THREAD

**Issue by zagr0** [kha7iq/drl-exporter#7]
**Describe the bug**

Its not actually a bug, but current latest docker image version based on the year old alpine image that contains few high severity vulnerabilities. Could you please release a new version in order to include security patches?

Here is GKE security scanner result for the current image:
<img width="867" alt="image" src="https://github.com/user-attachments/assets/13dfe125-ee91-4c35-8338-c9662128ff15">

Would be really great if you are able to release it regularly for security reasons.
Thank you in advance!

**Comment by kha7iq** [comment]
@zagr0  Thank you for letting me know. 
I will update the image.

**Comment by kha7iq** [comment]
Base image has been updated to `3.20.2`.  https://github.com/kha7iq/drl-exporter/pull/8
For future i will look into automating this.

**Comment by zagr0** [comment]
Thank you very much for the quick upgrade!
Would be also great to have the helm chart version updated as part of release or planned automation. To use actual version instead of latest tag from values.
https://github.com/kha7iq/drl-exporter/blob/master/deploy/chart/Chart.yaml#L16

**Comment by kha7iq** [comment]
I am already working on creating a new chart as this one is pretty old now. 
Hopefully will be available by the end of day today.

**Comment by kha7iq** [comment]
The chart has been moved to a separate repository, which you can find here: [drl-exporter chart repository](https://github.com/kha7iq/charts/tree/main/charts/drl-exporter). Rebuilding the chart for every release isn't feasible unless there are specific changes that require it.

However, you can easily set the desired image tag during installation by using the following command:
```bash
helm repo add lmno http://charts.lmno.pk
helm install drl-exporter lmno/drl-exporter --set image.tag=v2.1.3
```
his allows you to specify the exact version you need without requiring a chart rebuild.

**Comment by zagr0** [comment]
Thank you!
